### PR TITLE
feat(adding new page): created a new page for displaying cards

### PR DESCRIPTION
**Pull request by TCHE614**
### Purpose
Created the page that will display the card statements.

[HRT-31](https://softeng761team5.atlassian.net/browse/HRT-31?atlOrigin=eyJpIjoiMGEzYzFjODgwMWU5NDg1OWI4OTdhMmEwYTBjODczYzYiLCJwIjoiaiJ9)
[](https://softeng761team5.atlassian.net/browse/HRT-27)

### Approach
- Created the display cards page following the hi-fi designs
- Added a link from the homepage to the display page (temporary approach to the redirection)
- Created a switch for redirection
- Created a prop for text changing using states(I think this approach could be useful) 

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Does this PR involve a UI change?

- [x] Yes
- [ ] No

#### Screenshot(s) of UI before this PR
N/A

#### Screenshot(s) of UI after this PR
image

### CODE REVIEW

**Review by gargi-bansal — CHANGES_REQUESTED** [review]
Hey, you did a really good job with the UI. I just have a few nit-picky things that I think would be nice to fix up! Sorry, it looks like a really long list but should be simple changes :)
- Could the header be fixed to the top of the page? Also, the font for the "HeaRT" text needs to be changed to match the hi-fi designs. Have a look at the Homepage.css for the font name. Or tbh you could leave this as we will create a reusable Header component that can be used in all the pages for consistency.
- Might be best to encapsulate the rest of the components (excluding the header) in a div that extends to the full width and height of the page. (On my screen, the page only takes up half of the browser window space).
- The background colour of the window isn't white (it's a very slight purple) so that will need to be fixed up. Only the cards themselves have a white background.
- Also, some padding on the inside of the cards would look nice so that the text isn't too close to the ends of the cards!
- You could also give the Cards themselves a "min-height" of around 15vh instead of a "height" of 33vh and that would help with the responsiveness that you were trying to solve

**Comment by TCHE614** [comment]
Thanks, Gargi for the feedback it was really useful! :) I have incorporated the feedback into the PR now here is an image of it. 
image

**Review by gargi-bansal — CHANGES_REQUESTED** [review]
Looks good to me, one other minor thing I noticed was when you resize the browser window horizontally to be quite thin, the "Pick a statement" text changes to left-aligned from centre-aligned.
I think you'll need to add "text-align: center" to the statement text to fix that. 
Oh and I'm not 100% sure what the usual conventions for URL paths are but I think its lowercase, hyphen separated (so "display-cards" instead of "DisplayCards")? I could be wrong though, might be best to confirm with someone else.

I'll approve the PR once you get these changes in :)

**Review by mitchfaulcon — CHANGES_REQUESTED** [review]
Other than Gargi's changes, it might also be good to have the mouse change to the pointer over the whole card rather than just the text

**Comment by TCHE614** [comment]
Yep changed the pointer to over the whole card and also fixed the text alignment for the statement thanks Gargi and Mitchell. I'm not sure if we discussed how we are structuring the URL paths so that can be changed later when we decide on a format. :)

**Review by mitchfaulcon — APPROVED** [review]
Sweet looks good now

**Review by gargi-bansal — APPROVED** [review]
lgtm!

**Pull request merged**
