### PR TITLE
Hrt 94 url error handling

### PR DESCRIPTION
**Pull request by lucycy98**
### Purpose

when you enter a random URL with invalid course / chart ID, the app displays an error.

[HRT-94](https://softeng761team5.atlassian.net/browse/HRT-94)

### Approach

- if response code is not 200, we redirect to dashboard (easy fix).

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Does this PR involve a UI change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by mitchfaulcon — CHANGES_REQUESTED** [review]
Everything seems to be mostly functional, but I've noticed that the app doesn't redirect correctly for pages where the chartID is incorrect, e.g the preview page is just empty when the chartID is invalid

**Comment by lucycy98** [comment]
> Everything seems to be mostly functional, but I've noticed that the app doesn't redirect correctly for pages where the chartID is incorrect, e.g the preview page is just empty when the chartID is invalid

true good point thank you! Done

**Review by michellemtan — APPROVED** [review]
LGTM - Tested it and works! :)

**Review by mitchfaulcon — APPROVED** [review]
Thanks for the changes :) looks good now!

**Pull request merged**
