### PR TITLE
Hrt 41 dynamic display cards

### PR DESCRIPTION
**Pull request by gargi-bansal**
### Purpose

Users need to be able to complete the dimensions in the game so this feature allows them to go back and forth through the dimensions.

[HRT-41](https://softeng761team5.atlassian.net/browse/HRT-41)

### Approach
Changed the DisplayCards and Dimension to use the dummy data and types. Back, Skip and Next buttons work.
Progress bar updates based on the progress made.

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Does this PR involve a UI change?

- [x] Yes
- [ ] No

#### Screenshot(s) of UI before this PR
Screen Shot 2020-09-29 at 7 06 51 PM

#### Screenshot(s) of UI after this PR
Screen Shot 2020-09-29 at 7 05 06 PM
Screen Shot 2020-09-29 at 7 05 40 PM

### CODE REVIEW

**Review by mitchfaulcon — CHANGES_REQUESTED** [review]
Looks really good! Just one thing I noticed is that you can keep clicking the cards on one dimension and the completed count keeps going up, so you can end up with 20/10 completed on the first dimension

**Comment by gargi-bansal** [comment]
> Looks really good! Just one thing I noticed is that you can keep clicking the cards on one dimension and the completed count keeps going up, so you can end up with 20/10 completed on the first dimension

@mitchfaulcon whoopsie, thanks for catching that! I'll fix it now

**Review by mitchfaulcon — APPROVED** [review]
Thanks for that fix :) approved

**Review by lucycy98 — APPROVED** [review]
LGTM :)

**Pull request merged**
