### PR TITLE
feat(front end): add types to dimensions and associate them with colours

### PR DESCRIPTION
**Pull request by gargi-bansal**
Add types to dimensions and associate them with colours

BREAKING CHANGE: Function parameters have changed for getColours

### Purpose

Display dimension types and associate the two different types with two different colours.
[HRT-76](https://softeng761team5.atlassian.net/browse/HRT-76)

### Approach

Change getColours function and change CSS

### Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

May need to update any parameters passed into the getColours function in your branch if you've added it in any other location.

#### Does this PR involve a UI change?

- [x] Yes
- [ ] No

#### Screenshot(s) of UI before this PR
Screen Shot 2020-10-02 at 8 18 59 PM

#### Screenshot(s) of UI after this PR
Screen Shot 2020-10-02 at 8 10 37 PM
Screen Shot 2020-10-02 at 8 10 55 PM

### CODE REVIEW

**Comment by mitchfaulcon** [comment]
Do our colours need to match Claire's? Or is it fine just having them 2 different colours

**Comment by gargi-bansal** [comment]
> Do our colours need to match Claire's? Or is it fine just having them 2 different colours

@mitchfaulcon she said any were fine as long as they were distinct

**Review by mitchfaulcon — APPROVED** [review]
Looks good to me 😀

**Review by EricPedrido — APPROVED** [review]
LGTM

**Pull request merged**
