### PR TITLE
feat(front end): commenting 

### PR DESCRIPTION
**Pull request by gargi-bansal**
### Purpose

Commented the front end code for code quality

### Approach

Complicated code has explanations detailing what is happening
Renamed PlayReason to CreateChart and updated URLs, etc

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Does this PR involve a UI change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by preetpatel — DISMISSED** [review]
Kinda terrified by the amount of comments but if it pleases the TA's, im game 🙃

**Review by michellemtan — DISMISSED** [review]
Looks great, Gargi you're actually a beast!! Do we want comments explaining the classes/components? Cause Im happy to do that in the morning!

**Comment by gargi-bansal** [comment]
> Looks great, Gargi you're actually a beast!! Do we want comments explaining the classes/components? Cause Im happy to do that in the morning!

@michellemtan I can just add those in now. Tbh already did that in the wiki page for Pages & Components, so should be a simple copy and paste

**Review by preetpatel — APPROVED** [review]

**Review by michellemtan — APPROVED** [review]
Awesome and the refactoring works for me!

**Pull request merged**
